project:
  type: website
  output-dir: docs
  resources:
    - ".nojekyll"
    - "google5b4fc1ff0d25fe09.html"
    - "images/**"
    - "files/**"
    
website:
  title: "Mathias Abitbol"
  site-url: "https://mathias-abitbol.github.io"
  favicon: images/portrait.jpeg

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: media.qmd
        text: Media & Policy
      - href: files/CV.pdf
        text: Resume

  page-footer:
    center: "© 2026 Mathias Abitbol"

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    link-external-newwindow: true
    smooth-scroll: true